CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(300),
    done BOOLEAN NOT NULL DEFAULT 0,            --0: DEFAULT, 1:TRUE
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

